Add check format in pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -79,6 +79,43 @@ jobs:
         echo "::set-output name=version::$VERSION"
         echo $VERSION
 
+  format:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+      with:
+        ref: ${{ github.ref }}
+        fetch-depth: 0
+
+    - name: Install .NET Core
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: 6.x
+
+    - name: Install ReSharper
+      run: |
+        dotnet tool install -g JetBrains.ReSharper.GlobalTools
+
+    - name: Reformat
+      run: |
+        jb cleanupcode ArmoniK.Core.sln
+
+    - name: Check Diff
+      run: |
+        DIFF="$(git status --porcelain --untracked-files=no)"
+
+        if [ -z "$DIFF" ]; then
+          echo "OK: Format is clean"
+        else
+          echo "Error: Format was not clean"
+          echo "List of files:"
+          echo "$DIFF"
+          # Uncomment the following line when repo is ready
+          #exit 1
+        fi
+
+
   tests:
     strategy:
       matrix:
